"""initial schema

Revision ID: f28d865e5229
Revises: 
Create Date: 2026-09-24 14:15:25.780167
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f28d865e5229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleanup_tasks_project_id'), 'cleanup_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_cleanup_tasks_status'), 'cleanup_tasks', ['status'], unique=False)
    op.create_table('knowledge_cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('applicable_intents', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('pitfalls', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_cards_topic'), 'knowledge_cards', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_subject'), 'users', ['subject'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rights_note', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('container', sa.String(length=32), nullable=False),
    sa.Column('video_codec', sa.String(length=32), nullable=False),
    sa.Column('audio_codec', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('is_vfr', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rejection_code', sa.String(length=64), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('rights_note', sa.Text(), nullable=False),
    sa.Column('probe', sa.JSON(), nullable=False),
    sa.Column('is_demo_prebuilt', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result_type', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('deleted_marker', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost_cny', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_job_owner_idem')
    )
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('knowledge_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=False),
    sa.Column('parent_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('media', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('is_demo_prebuilt', sa.Boolean(), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'version', name='uq_analysis_asset_version')
    )
    op.create_index(op.f('ix_analyses_asset_id'), 'analyses', ['asset_id'], unique=False)
    op.create_index(op.f('ix_analyses_owner_id'), 'analyses', ['owner_id'], unique=False)
    op.create_index(op.f('ix_analyses_project_id'), 'analyses', ['project_id'], unique=False)
    op.create_table('job_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_stages_job_id'), 'job_stages', ['job_id'], unique=False)
    op.create_table('model_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('provider_request_id', sa.String(length=160), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('estimated_cost_cny', sa.Float(), nullable=False),
    sa.Column('price_version', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_calls_job_id'), 'model_calls', ['job_id'], unique=False)
    op.create_index(op.f('ix_model_calls_owner_id'), 'model_calls', ['owner_id'], unique=False)
    op.create_table('learning_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('submission_requirements', sa.JSON(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('reference_metrics', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('knowledge_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_tasks_analysis_id'), 'learning_tasks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_learning_tasks_owner_id'), 'learning_tasks', ['owner_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('shot_ref', sa.String(length=32), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('shot_scale', sa.String(length=32), nullable=False),
    sa.Column('camera_motion', sa.String(length=32), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('alternative', sa.Text(), nullable=False),
    sa.Column('narrative_function', sa.String(length=64), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('transcript_segments', sa.JSON(), nullable=False),
    sa.Column('frame_keys', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('knowledge_ids', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_analysis_id'), 'shots', ['analysis_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('submission_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('learner_reason', sa.Text(), nullable=False),
    sa.Column('storyboard_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['learning_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_asset_id'), 'submissions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_submissions_owner_id'), 'submissions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('alignments', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('storyboard_metrics', sa.JSON(), nullable=False),
    sa.Column('reference_metrics', sa.JSON(), nullable=False),
    sa.Column('submission_metrics', sa.JSON(), nullable=False),
    sa.Column('constraint_results', sa.JSON(), nullable=False),
    sa.Column('task_snapshot', sa.JSON(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_owner_id'), 'feedback', ['owner_id'], unique=False)
    op.create_index(op.f('ix_feedback_submission_id'), 'feedback', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_submission_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_owner_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_owner_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_asset_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_shots_analysis_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_learning_tasks_owner_id'), table_name='learning_tasks')
    op.drop_index(op.f('ix_learning_tasks_analysis_id'), table_name='learning_tasks')
    op.drop_table('learning_tasks')
    op.drop_index(op.f('ix_model_calls_owner_id'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_job_id'), table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index(op.f('ix_job_stages_job_id'), table_name='job_stages')
    op.drop_table('job_stages')
    op.drop_index(op.f('ix_analyses_project_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_owner_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_asset_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index('ix_jobs_status_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_cards_topic'), table_name='knowledge_cards')
    op.drop_table('knowledge_cards')
    op.drop_index(op.f('ix_cleanup_tasks_status'), table_name='cleanup_tasks')
    op.drop_index(op.f('ix_cleanup_tasks_project_id'), table_name='cleanup_tasks')
    op.drop_table('cleanup_tasks')
    # ### end Alembic commands ###
